import uis from './common';

uis.run([
  '$templateCache',
  function($templateCache) {
    $templateCache.put(
      'bootstrap/choices.tpl.html',
      require('./themes/bootstrap/choices.tpl.html')
    );
    $templateCache.put(
      'bootstrap/footer.tpl.html',
      require('./themes/bootstrap/footer.tpl.html')
    );
    $templateCache.put(
      'bootstrap/header.tpl.html',
      require('./themes/bootstrap/header.tpl.html')
    );
    $templateCache.put(
      'bootstrap/choices.tpl.html',
      require('./themes/bootstrap/choices.tpl.html')
    );
    $templateCache.put(
      'bootstrap/match-multiple.tpl.html',
      require('./themes/bootstrap/match-multiple.tpl.html')
    );
    $templateCache.put(
      'bootstrap/match.tpl.html',
      require('./themes/bootstrap/match.tpl.html')
    );
    $templateCache.put(
      'bootstrap/no-choice.tpl.html',
      require('./themes/bootstrap/no-choice.tpl.html')
    );
    $templateCache.put(
      'bootstrap/select-multiple.tpl.html',
      require('./themes/bootstrap/select-multiple.tpl.html')
    );
    $templateCache.put(
      'bootstrap/select.tpl.html',
      require('./themes/bootstrap/select.tpl.html')
    );

    $templateCache.put(
      'bootstrap4/choices.tpl.html',
      require('./themes/bootstrap4/choices.tpl.html')
    );
    $templateCache.put(
      'bootstrap4/footer.tpl.html',
      require('./themes/bootstrap4/footer.tpl.html')
    );
    $templateCache.put(
      'bootstrap4/header.tpl.html',
      require('./themes/bootstrap4/header.tpl.html')
    );
    $templateCache.put(
      'bootstrap4/choices.tpl.html',
      require('./themes/bootstrap4/choices.tpl.html')
    );
    $templateCache.put(
      'bootstrap4/match-multiple.tpl.html',
      require('./themes/bootstrap4/match-multiple.tpl.html')
    );
    $templateCache.put(
      'bootstrap4/match.tpl.html',
      require('./themes/bootstrap4/match.tpl.html')
    );
    $templateCache.put(
      'bootstrap4/no-choice.tpl.html',
      require('./themes/bootstrap4/no-choice.tpl.html')
    );
    $templateCache.put(
      'bootstrap4/select-multiple.tpl.html',
      require('./themes/bootstrap4/select-multiple.tpl.html')
    );
    $templateCache.put(
      'bootstrap4/select.tpl.html',
      require('./themes/bootstrap4/select.tpl.html')
    );
    $templateCache.put(
      'select2/choices.tpl.html',
      require('./themes/select2/choices.tpl.html')
    );
    $templateCache.put(
      'select2/footer.tpl.html',
      require('./themes/select2/footer.tpl.html')
    );
    $templateCache.put(
      'select2/header.tpl.html',
      require('./themes/select2/header.tpl.html')
    );
    $templateCache.put(
      'select2/choices.tpl.html',
      require('./themes/select2/choices.tpl.html')
    );
    $templateCache.put(
      'select2/match-multiple.tpl.html',
      require('./themes/select2/match-multiple.tpl.html')
    );
    $templateCache.put(
      'select2/match.tpl.html',
      require('./themes/select2/match.tpl.html')
    );
    $templateCache.put(
      'select2/no-choice.tpl.html',
      require('./themes/select2/no-choice.tpl.html')
    );
    $templateCache.put(
      'select2/select-multiple.tpl.html',
      require('./themes/select2/select-multiple.tpl.html')
    );
    $templateCache.put(
      'select2/select.tpl.html',
      require('./themes/select2/select.tpl.html')
    );
    $templateCache.put(
      'selectize/choices.tpl.html',
      require('./themes/selectize/choices.tpl.html')
    );
    $templateCache.put(
      'selectize/footer.tpl.html',
      require('./themes/selectize/footer.tpl.html')
    );
    $templateCache.put(
      'selectize/header.tpl.html',
      require('./themes/selectize/header.tpl.html')
    );
    $templateCache.put(
      'selectize/choices.tpl.html',
      require('./themes/selectize/choices.tpl.html')
    );
    $templateCache.put(
      'selectize/match-multiple.tpl.html',
      require('./themes/selectize/match-multiple.tpl.html')
    );
    $templateCache.put(
      'selectize/match.tpl.html',
      require('./themes/selectize/match.tpl.html')
    );
    $templateCache.put(
      'selectize/no-choice.tpl.html',
      require('./themes/selectize/no-choice.tpl.html')
    );
    $templateCache.put(
      'selectize/select-multiple.tpl.html',
      require('./themes/selectize/select-multiple.tpl.html')
    );
    $templateCache.put(
      'selectize/select.tpl.html',
      require('./themes/selectize/select.tpl.html')
    );
  }
]);
